PACKAGE_NAME="r8152"
PACKAGE_VERSION="2.22.1"

BUILT_MODULE_NAME[0]="r8152"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/usb"

MAKE[0]="'make' KERNELDIR=/lib/modules/${kernelver}/build modules"
POST_INSTALL="dkms-install-rules"

AUTOINSTALL="yes"
